language: go
sudo: true
go:
  - 1.5

script:
  - make test

install:
 - go get -d -t -v ./...
 - go get github.com/gopherjs/gopherjs
 - go get github.com/gopherjs/jquery
 - make buildjs

before_script:
    - "curl -sSL https://github.com/goodeggs/travis-utils/raw/master/chromedriver.sh | sh"
    - "wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar"
    - "java -jar selenium-server-standalone-2.48.2.jar> /dev/null &"
    - sleep 5