language: go
go:
  - 1.5

addons:
  sauce_connect: true

script:
  - make test

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
 - go get -d -t -v ./...
 - go get github.com/gopherjs/gopherjs
 - go get github.com/gopherjs/jquery
 - make buildjs