language: go
sudo: true
go:
  - 1.5

script:
  - make test

install:
 - go get -d -t -v ./...
 - go get github.com/gopherjs/gopherjs
 - go get github.com/gopherjs/jquery
 - make buildjs

before_script:
    - sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
    - "sh -e /etc/init.d/xvfb start"
    - "export DISPLAY=:99.0"
    - "wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar"
    - "wget http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux32.zip && unzip chromedriver_linux32.zip"
    - "java -jar selenium-server-standalone-2.48.2.jar -Dwebdriver.chrome.driver='chromedriver' > /dev/null &"
    - sleep 5