language: go
sudo: false
go:
  - 1.5

script:
  - make test

install:
 - go get -d -t -v ./...
 - go get github.com/gopherjs/gopherjs
 - go get github.com/gopherjs/jquery
 - make buildjs

before_script:
    - "wget http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip && unzip chromedriver_linux32_23.0.1240.0.zip && sudo mv chromedriver /usr/bin"
    - "sh -e /etc/init.d/xvfb start"
    - "export DISPLAY=:99.0"
    - "wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar"
    - "java -jar selenium-server-standalone-2.48.2.jar > /dev/null &"
    - sleep 5