language: go
sudo: true
go:
  - 1.5

addons:
  sauce_connect: true

script:
  - make test

install:
 - go get -d -t -v ./...
 - go get github.com/gopherjs/gopherjs
 - go get github.com/gopherjs/jquery
 - make buildjs